export const dummyBooks = [{
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    priority: "Must read!",
    id: 0,
    read: true,
    dateRead: "02/02/2022",
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    priority: "Want to read",
    id: 1,
    read: false,
    dateRead: null,
  },
  {
    title: "1984",
    author: "George Orwell",
    priority: "Must read!",
    id: 2,
    read: true,
    dateRead: "01/01/2022",
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    priority: "Might read",
    id: 3,
    read: false,
    dateRead: null,
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    priority: "Want to read",
    id: 4,
    read: false,
    dateRead: null,
  }];