export const dummyBooks = [
  {
    title: "The Secret History",
    author: "Donna Tartt",
    priority: "Must read!",
    id: 0,
    read: true,
    dateRead: "02/02/2022",
  },
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    priority: "Want to read",
    id: 1,
    read: false,
    dateRead: null,
  },
  {
    title: "Great Expectations",
    author: "Charles Dickens",
    priority: "Must read!",
    id: 2,
    read: true,
    dateRead: "01/01/2022",
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    priority: "Might read",
    id: 3,
    read: false,
    dateRead: null,
  },
  {
    title: "The Marriage Plot",
    author: "Jeffrey Eugenides",
    priority: "Want to read",
    id: 4,
    read: false,
    dateRead: null,
  },
];
